### ISSUE TITLE
Reinstalled arch minimal. Used install.sh -all no GUI

### ISSUE THREAD

**Issue by tasmaniandaemon** [yutkat/dotfiles#3570]
as the title says

**Comment by yutkat** [comment]
Why do you write the same thing in Discussions and Issues? And I can't support you because you don't provide enough details.

If you keep doing that, I have to block you.

**Comment by ghost** [comment]
I'm sorry, i didn't try to offend you nor make damage to your github repository. I'm just getting started, all of this is new to me. The issue was on nvidia drivers, so i spent all day making it work. I would appreciate if you could post a discord server or telegram, so we could ask questions. Thank you for your work, it does look amazing. I don't really understand how everything work or can be configured.

**Comment by yutkat** [comment]
You can ask me questions in Issue or Discussion. However, I would like some more information and would like to discuss it in one place.

Also, unfortunately, I don't use nVidia GPUs (I don't use it because it doesn't work well on Linux), so I can't help you...
